---
php_version: '8.3'
php_default_version_debian: "{{ php_version }}"
php_enable_webserver: false
php_webserver_daemon: "nginx"

php_install_recommends: no

php_enable_php_fpm: true
php_fpm_state: started
php_fpm_handler_state: restarted
php_fpm_enabled_on_boot: true
# php_fpm_listen: "/var/run/php-fpm.$pool.sock"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
php_fpm_pm_max_requests: 100


php_packages:
     - "php{{ php_version }}"
     - "php{{ php_version }}-amqp"
     - "php{{ php_version }}-apcu"
     - "php{{ php_version }}-ast"
     - "php{{ php_version }}-bcmath"
     - "php{{ php_version }}-bz2"
     - "php{{ php_version }}-cgi"
     - "php{{ php_version }}-cli"
     - "php{{ php_version }}-common"
     - "php{{ php_version }}-curl"
     - "php{{ php_version }}-dba"
     - "php{{ php_version }}-decimal"
     - "php{{ php_version }}-dev"
     - "php{{ php_version }}-dio"
     - "php{{ php_version }}-ds"
     - "php{{ php_version }}-enchant"
     - "php{{ php_version }}-excimer"
     - "php{{ php_version }}-fpm"
     - "php{{ php_version }}-gd"
     - "php{{ php_version }}-gearman"
#     - "php{{ php_version }}-gmagick"
     - "php{{ php_version }}-gmp"
     - "php{{ php_version }}-gnupg"
     - "php{{ php_version }}-grpc"
     - "php{{ php_version }}-http"
     - "php{{ php_version }}-igbinary"
     - "php{{ php_version }}-imagick"
     - "php{{ php_version }}-imap"
     - "php{{ php_version }}-inotify"
     - "php{{ php_version }}-interbase"
     - "php{{ php_version }}-intl"
     - "php{{ php_version }}-ldap"
     - "php{{ php_version }}-libvirt-php"
     - "php{{ php_version }}-lz4"
     - "php{{ php_version }}-mailparse"
     - "php{{ php_version }}-maxminddb"
     - "php{{ php_version }}-mbstring"
     - "php{{ php_version }}-mcrypt"
     - "php{{ php_version }}-memcache"
     - "php{{ php_version }}-memcached"
     - "php{{ php_version }}-mongodb"
     - "php{{ php_version }}-msgpack"
     - "php{{ php_version }}-mysql"
     - "php{{ php_version }}-oauth"
     - "php{{ php_version }}-odbc"
     - "php{{ php_version }}-opcache"
     - "php{{ php_version }}-opentelemetry"
     - "php{{ php_version }}-pcov"
     - "php{{ php_version }}-pgsql"
     - "php{{ php_version }}-phalcon"
     - "php{{ php_version }}-phalcon5"
     - "php{{ php_version }}-phpdbg"
     - "php{{ php_version }}-pinba"
#     - "php{{ php_version }}-pq"
     - "php{{ php_version }}-protobuf"
     - "php{{ php_version }}-ps"
     - "php{{ php_version }}-pspell"
     - "php{{ php_version }}-psr"
     - "php{{ php_version }}-raphf"
     - "php{{ php_version }}-rdkafka"
     - "php{{ php_version }}-readline"
     - "php{{ php_version }}-redis"
     - "php{{ php_version }}-rrd"
     - "php{{ php_version }}-smbclient"
     - "php{{ php_version }}-snmp"
     - "php{{ php_version }}-soap"
     - "php{{ php_version }}-solr"
     - "php{{ php_version }}-sqlite3"
     - "php{{ php_version }}-ssh2"
     - "php{{ php_version }}-stomp"
     - "php{{ php_version }}-swoole"
     - "php{{ php_version }}-sybase"
     - "php{{ php_version }}-tidy"
     - "php{{ php_version }}-uopz"
     - "php{{ php_version }}-uploadprogress"
     - "php{{ php_version }}-uuid"
     - "php{{ php_version }}-vips"
     - "php{{ php_version }}-xdebug"
     - "php{{ php_version }}-xhprof"
     - "php{{ php_version }}-xml"
     - "php{{ php_version }}-xmlrpc"
     - "php{{ php_version }}-xsl"
#     - "php{{ php_version }}-yac"
     - "php{{ php_version }}-yaml"
     - "php{{ php_version }}-zip"
     - "php{{ php_version }}-zmq"
     - "php{{ php_version }}-zstd"
php_packages_extra:
     - nginx
     - make
     - pkgconf

php_pear_libraries:
     - XML_Parser
     - XML_Wddx
