roles:
  - src: https://github.com/geerlingguy/ansible-role-php.git
    scm: git
    name: ansible-role-php

  - src: https://github.com/geerlingguy/ansible-role-php-versions.git
    scm: git
    name: ansible-role-php-versions

  - src: https://github.com/geerlingguy/ansible-role-mysql.git
    scm: git
    name: ansible-role-mysql

  - src: https://github.com/do-community/ansible-playbooks.git
    scm: git
    name: ansible-lemp  