---
#Преднастройка
- name: Преднастройка пакетного менеджера aptitude
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

# Установка Nginx
- name: Установка последней версии Nginx
  apt: name=nginx state=latest

- name: Запуск Nginx
  service:
    name: nginx
    state: started

# Настройка Nginx
- name: Скопировать и переименовать Nginx конфиг
  template:
    src: "web.j2"
    dest: "/etc/nginx/sites-available/web"
